apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  finalizers:
  - elbv2.k8s.aws/resources
  generation: 1
  name: ingress-external-tgb
  namespace: nginx-ingress-external
spec:
  ipAddressType: ipv4
  nodeSelector:
    matchLabels:
      beta.kubernetes.io/os: linux
  serviceRef:
    name: nginx-ingress-external-ingress-nginx-controller
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:647255248014:targetgroup/prod-lb-tg/9e7ef3c46b4de334
  targetType: instance
