on:
  push:
    branches:
      - '*'
jobs:
  github-example-tags:
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Tag Name example
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         echo "Tag name from github.repository: ${{ github.repository }}" 
         echo "Tag github.event.repository.name ${{ github.event.repository.name }}"
         echo "FY$(date '+%y')Q$(date '+%q')FR-${{ vars.RELEASE_ITERATION }}"
         echo ${{ github.run_id }}
         echo ${{ github.run_number }}
         echo ${{ github.run_attempt }}     
         echo "RELEASE_ITERATION=prabhat" >> $GITHUB_ENV

         x = $((vars.COUNTER+1))
         echo $x

        
     - name: run curl
       run: gh api --method PATCH -H "Accept:application/vnd.github+json" -H "X-GitHub-Api-Version:2022-11-28" /repos/${{ github.repository }}/actions/variables/COUNTER -f name='COUNTER' -f value=${{ env.SEQ_COUNTER }}
       env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_SECRET }}
          SEQ_COUNTER: expr ${{ vars.COUNTER }} + 1

         
#        run: |
#           echo "https://api.github.com/repos/${{ github.repository }}/actions/variables/COUNTER"
#           curl -L  \
#           -X PATCH \
#           -H "Accept: application/vnd.github+json" \
#           -H "Authorization: Bearer asd"\
#           -H "X-GitHub-Api-Version: 2022-11-28" \
#           https://api.github.com/repos/prabhat2k15/terraform/actions/variables/COUNTER \
#           -d '{"name":"COUNTER","value":"prabhat"}'
          





