on:
  push:
    branches:
      - '*'
jobs:
  github-example-tags:
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Tag Name example
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         echo "Tag name from github.repository: ${{ github.repository }}" 
         echo "Tag github.event.repository.name ${{ github.event.repository.name }}"
         echo "FY$(date '+%y')Q$(date '+%q')FR-${{ vars.RELEASE_ITERATION }}"
         echo ${{ github.run_id }}
         echo ${{ github.run_number }}
         echo ${{ github.run_attempt }}     
         echo "RELEASE_ITERATION=prabhat" >> $GITHUB_ENV
         echo ${{ vars.QUARTER }} != $(date '+%q')
        
     - name: run curl
       run: |
        expr ${{ vars.COUNTER }} + 1 > counter.txt
        gh api --method PATCH -H "Accept:application/vnd.github+json" -H "X-GitHub-Api-Version:2022-11-28" /repos/${{ github.repository }}/actions/variables/COUNTER -f name='COUNTER' -f value=`cat counter.txt`
       env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_SECRET }}
          
     - name: docker push
       env:  
        Q: $(date '+%q')
       if:  vars.QUARTER }} != env.Q
       run: |
        echo ${{ env.Q }}
        echo "jfrog.io/${{ github.event.repository.name }}-docker/${{ github.event.repository.name }}:FY$(date '+%y')Q$(date '+%q')FR-${{ vars.COUNTER }}"
     - name: docker push
       if: "${{ vars.QUARTER }} != $(date '+%q')"
       run: |
        gh api --method PATCH -H "Accept:application/vnd.github+json" -H "X-GitHub-Api-Version:2022-11-28" /repos/${{ github.repository }}/actions/variables/COUNTER -f name='COUNTER' -f value=0
       env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_SECRET }}
          Q: $(date '+%q')
         

          





