on:
  push:
    branches:
      - '*'
jobs:
  github-example-tags:
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Tag Name example
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         echo "Tag name from github.repository: ${{ github.repository }}" 
         echo "Tag github.event.repository.name ${{ github.event.repository.name }}"
         echo "FY$(date '+%y')Q$(date '+%q')FR-${{ vars.RELEASE_ITERATION }}"

     - name: Output Run ID
       run: echo ${{ github.run_id }}
     - name: Output Run Number
       run: echo ${{ github.run_number }}
     - name: Output Run Attempt
       run: echo ${{ github.run_attempt }}     




